In [1]:
%pip install pandas

Collecting pandas
  Downloading pandas-3.1.0-cp314-cp314-win_amd64.whl.metadata (18 kB)
Collecting numpy>=2.3.3 (from pandas)
  Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.9.0 in c:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\.venv\Lib\site-packages (from pandas) (3.0.0)
Requirement already satisfied: tzdata in c:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\.venv\Lib\site-packages (from pandas) (2026.5)
Requirement already satisfied: six>=1.6 in c:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\.venv\Lib\site-packages (from python-dateutil>=2.9.0->pandas) (1.17.0)
Downloading pandas-3.1.0-cp314-cp314-win_amd64.whl (10.9 MB)
   ---------------------------------------- 0.0/10.9 MB ? eta -:--:--
    --------------------------------------- 0.3/10.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/10.9 MB 2.4 MB/s eta 0:00:05
   --- ------------------------------------ 1.0/10.9 MB 2.5 MB/s eta 0:00:05
   ----- ---------------------------------- 1.6/10.9 MB 2.1 MB/s eta 0:00:05
   ------- -------------------------------- 2.1/10.9 MB 2.3 MB/s eta 0:00:04
   -------- ------------------------------- 2.4/10.9 MB 2.1 MB/s eta 0:00:05
   ----------- ---------------------------- 3.1/10.9 MB 2.4 MB/s eta 0:00:04
   -------------- ------------------------- 3.9/10.9 MB 2.6 MB/s eta 0:00:03
   ----------------- ---------------------- 4.7/10.9 MB 2.8 MB/s eta 0:00:03
   --------------------- ------------------ 5.8/10.9 MB 3.0 MB/s eta 0:00:02
   ------------------------ --------------- 6.6/10.9 MB 3.1 MB/s eta 0:00:02
   -------------------------- ------------- 7.3/10.9 MB 3.1 MB/s eta 0:00:02
   --------------------------- ------------ 7.6/10.9 MB 3.1 MB/s eta 0:00:02
   ------------------------------- -------- 8.7/10.9 MB 3.1 MB/s eta 0:00:01
   -------------------------------- ------- 8.9/10.9 MB 3.1 MB/s eta 0:00:01
   ----------------------------------- ---- 9.7/10.9 MB 3.0 MB/s eta 0:00:01
   ------------------------------------- -- 10.2/10.9 MB 3.1 MB/s eta 0:00:01
   ---------------------------------------- 10.9/10.9 MB 3.1 MB/s  0:00:03
Downloading numpy-2.5.4-cp314-cp314-win_amd64.whl (12.7 MB)
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   --- ------------------------------------ 1.0/12.7 MB 5.9 MB/s eta 0:00:02
   ---- ----------------------------------- 1.3/12.7 MB 4.2 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.7 MB 3.6 MB/s eta 0:00:03
   --------- ------------------------------ 3.1/12.7 MB 3.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.9/12.7 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 5.0/12.7 MB 4.1 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.7 MB 4.2 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.7 MB 4.2 MB/s eta 0:00:02
   ----------------------- ---------------- 7.6/12.7 MB 4.2 MB/s eta 0:00:02
   ------------------------ --------------- 7.9/12.7 MB 3.9 MB/s eta 0:00:02
   -------------------------- ------------- 8.4/12.7 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.7 MB 3.7 MB/s eta 0:00:01
   ------------------------------- -------- 10.0/12.7 MB 3.7 MB/s eta 0:00:01
   --------------------------------- ------ 10.5/12.7 MB 3.6 MB/s eta 0:00:01
   ----------------------------------- ---- 11.3/12.7 MB 3.6 MB/s eta 0:00:01
   ------------------------------------- -- 12.1/12.7 MB 3.7 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 3.7 MB/s  0:00:03
Installing collected packages: numpy, pandas

   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   ---------------------------------------- 0/2 [numpy]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   -------------------- ------------------- 1/2 [pandas]
   ---------------------------------------- 2/2 [pandas]

Successfully installed numpy-2.5.4 pandas-3.1.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
from pathlib import Path

carpeta = Path(r"C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results\Metricas\Convertidos")

# Buscar todos los CSV de interacciones, incluso en subcarpetas
archivos = sorted(carpeta.rglob("*_interacciones.csv"))

print(f"Archivos encontrados: {len(archivos)}")

# Leer todos los archivos
dataframes = []

for archivo in archivos:
    df = pd.read_csv(archivo, encoding="utf-8-sig")

    # Guardar de qué archivo proviene cada fila
    df["ArchivoOrigen"] = archivo.name

    dataframes.append(df)

# Unir los datos
if not dataframes:
    raise FileNotFoundError("No se encontraron archivos de interacciones")

df_final = pd.concat(dataframes, ignore_index=True)

# Guardar CSV unificado
salida = Path(r"C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results") / "interacciones_unificadas.csv"
df_final.to_csv(salida, index=False, encoding="utf-8-sig")

print(f"Total de interacciones: {len(df_final)}")
print(f"Participantes: {df_final['Participante'].nunique()}")
print(f"CSV guardado en: {salida}")

Archivos encontrados: 34
Total de interacciones: 5048
Participantes: 34
CSV guardado en: C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results\interacciones_unificadas.csv

In [3]:
# Número de interacciones por participante
df_final.groupby("Participante").size()

Participante
P001     132
P0011    138
P002     165
P003     169
P004     206
P005     154
P006     181
P007     109
P008     128
P010     115
P012     159
P013     192
P014     102
P015     132
P016     132
P017     138
P018     186
P019     145
P020     111
P021     152
P022     185
P023     121
P024     193
P025     147
P026     223
P027     117
P028     112
P029     110
P030     135
P031     181
P032     127
P033     131
P034     204
P036     116
dtype: int64

In [4]:
df_final.head(10)

,IdEvento,Participante,FechaHora,Minijuego,TipoAccion,Resultado,Dificultad,TiempoEsperado_s,TiempoReal_s,DesfaseTiming_s,ErrorTiming_s,TiempoReaccion_s,PrecisionEspacial,PrecisionDireccion,ManoCorrecta,LineaOrigen,ArchivoOrigen
0,2,P0011,2026-10-02 14:30:47.911,Alex,HammerTouch,Success,Normal,1.664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,Metrics_P0011_2026-10-02_14-30-44_interaccione...
1,4,P0011,2026-10-02 14:30:48.674,Alex,HammerTouch,Success,Normal,2.432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,Metrics_P0011_2026-10-02_14-30-44_interaccione...
2,5,P0011,2026-10-02 14:30:48.729,Alex,HammerTouch,Success,Normal,2.432,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,Metrics_P0011_2026-10-02_14-30-44_interaccione...
3,6,P0011,2026-10-02 14:30:49.440,Alex,HammerHit,Success,Normal,3.200,3.2115,0.0115,0.0115,NaN,NaN,NaN,NaN,11,Metrics_P0011_2026-10-02_14-30-44_interaccione...
4,7,P0011,2026-10-02 14:30:49.494,Alex,HammerTouch,Success,Normal,3.200,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12,Metrics_P0011_2026-10-02_14-30-44_interaccione...
5,8,P0011,2026-10-02 14:30:50.204,Alex,HammerHit,Failed,Normal,3.968,3.9759,0.0079,0.0079,NaN,NaN,NaN,NaN,13,Metrics_P0011_2026-10-02_14-30-44_interaccione...
6,9,P0011,2026-10-02 14:30:50.522,Alex,HammerTouch,Missed,Normal,3.968,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14,Metrics_P0011_2026-10-02_14-30-44_interaccione...
7,10,P0011,2026-10-02 14:30:50.954,Alex,HammerHit,Success,Normal,4.736,4.7261,-0.0099,0.0099,NaN,NaN,NaN,NaN,15,Metrics_P0011_2026-10-02_14-30-44_interaccione...
8,11,P0011,2026-10-02 14:30:50.996,Alex,HammerTouch,Success,Normal,4.736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,Metrics_P0011_2026-10-02_14-30-44_interaccione...
9,12,P0011,2026-10-02 14:30:51.705,Alex,HammerHit,Success,Normal,5.504,5.4766,-0.0274,0.0274,NaN,NaN,NaN,NaN,17,Metrics_P0011_2026-10-02_14-30-44_interaccione...

In [5]:
import pandas as pd

# Filtrar los tres minijuegos
minijuegos = ["Jeremy", "Shipi", "JuanAndres"]

df = df_final[
    df_final["Minijuego"].isin(minijuegos)
].copy()

# Convertir precisión de dirección a valores numéricos
df["PrecisionDireccion"] = pd.to_numeric(
    df["PrecisionDireccion"], errors="coerce"
)

# Convertir True = 1 y False = 0
df["ManoCorrectaNum"] = (
    df["ManoCorrecta"]
    .astype("string")
    .str.strip()
    .str.lower()
    .map({"true": 1, "false": 0})
)

# Agrupar por participante y minijuego
resultados = df.groupby(
    ["Participante", "Minijuego"], as_index=False
).agg(
    SumaDireccion=("PrecisionDireccion", "sum"),
    TotalDireccion=("PrecisionDireccion", "count"),
    SumaMano=("ManoCorrectaNum", "sum"),
    TotalMano=("ManoCorrectaNum", "count")
)

# Calcular los porcentajes
resultados["PrecisionDireccion_%"] = (
    resultados["SumaDireccion"] /
    resultados["TotalDireccion"].replace(0, float("nan")) * 100
).round(2)

resultados["ManoCorrecta_%"] = (
    resultados["SumaMano"] /
    resultados["TotalMano"].replace(0, float("nan")) * 100
).round(2)

# Seleccionar columnas finales
resultados_finales = resultados[
    ["Participante", "Minijuego",
     "PrecisionDireccion_%", "ManoCorrecta_%"]
]

display(resultados_finales)

    Participante   Minijuego  PrecisionDireccion_%  ManoCorrecta_%
0           P001      Jeremy                 75.00           87.50
1           P001  JuanAndres                 42.86           50.00
2           P001       Shipi                 18.18             NaN
3          P0011      Jeremy                 71.43           85.71
4          P0011  JuanAndres                 31.25           68.75
..           ...         ...                   ...             ...
97          P034  JuanAndres                 72.22           88.89
98          P034       Shipi                 58.82             NaN
99          P036      Jeremy                 87.50          100.00
100         P036  JuanAndres                 38.89           66.67
101         P036       Shipi                 41.67             NaN

[102 rows x 4 columns]

In [7]:
import pandas as pd

# Orden deseado de los minijuegos
orden = {
    "Shipi": 0,
    "JuanAndres": 1,
    "Jeremy": 2
}

nombres = {
    "Shipi": "Shipi",
    "JuanAndres": "Juan Andres",
    "Jeremy": "Jeremy"
}

# Ordenar por participante y minijuego
df_latex = resultados_finales.copy()
df_latex["Orden"] = df_latex["Minijuego"].map(orden)
df_latex = df_latex.sort_values(["Participante", "Orden"])

# Formatear porcentajes
def porcentaje(valor):
    if pd.isna(valor):
        return "---"
    return f"{valor:.2f}\\%"

# Generar filas LaTeX
filas = []
participante_anterior = None

for _, fila in df_latex.iterrows():
    participante = fila["Participante"]
    minijuego = nombres[fila["Minijuego"]]

    # Separar participantes con una línea vacía
    if participante_anterior is not None and participante != participante_anterior:
        filas.append("")

    direccion = porcentaje(fila["PrecisionDireccion_%"])
    mano = porcentaje(fila["ManoCorrecta_%"])

    if minijuego == "Shipi":
        mano = "---"

    linea = (
        f"{participante} & {minijuego:<11} & "
        f"{direccion} & {mano} " + r"\\ \hline"
    )

    filas.append(linea)
    participante_anterior = participante

# Mostrar resultado
latex_tabla = "\n".join(filas)
print(latex_tabla)

P001 & Shipi       & 18.18\% & --- \\ \hline
P001 & Juan Andres & 42.86\% & 50.00\% \\ \hline
P001 & Jeremy      & 75.00\% & 87.50\% \\ \hline

P0011 & Shipi       & 35.71\% & --- \\ \hline
P0011 & Juan Andres & 31.25\% & 68.75\% \\ \hline
P0011 & Jeremy      & 71.43\% & 85.71\% \\ \hline

P002 & Shipi       & 88.89\% & --- \\ \hline
P002 & Juan Andres & 70.59\% & 64.71\% \\ \hline
P002 & Jeremy      & 75.00\% & 100.00\% \\ \hline

P003 & Shipi       & 20.00\% & --- \\ \hline
P003 & Juan Andres & 35.71\% & 57.14\% \\ \hline
P003 & Jeremy      & 25.00\% & 100.00\% \\ \hline

P004 & Shipi       & 50.00\% & --- \\ \hline
P004 & Juan Andres & 100.00\% & 80.00\% \\ \hline
P004 & Jeremy      & 76.19\% & 85.71\% \\ \hline

P005 & Shipi       & 66.67\% & --- \\ \hline
P005 & Juan Andres & 55.56\% & 88.89\% \\ \hline
P005 & Jeremy      & 92.31\% & 84.62\% \\ \hline

P006 & Shipi       & 61.54\% & --- \\ \hline
P006 & Juan Andres & 63.16\% & 73.68\% \\ \hline
P006 & Jeremy      & 81.82\% & 90.91\% \\ \hline

P007 & Shipi       & 57.14\% & --- \\ \hline
P007 & Juan Andres & 38.89\% & 61.11\% \\ \hline
P007 & Jeremy      & 60.00\% & 100.00\% \\ \hline

P008 & Shipi       & 66.67\% & --- \\ \hline
P008 & Juan Andres & 69.57\% & 69.57\% \\ \hline
P008 & Jeremy      & 42.86\% & 100.00\% \\ \hline

P010 & Shipi       & 63.64\% & --- \\ \hline
P010 & Juan Andres & 33.33\% & 88.89\% \\ \hline
P010 & Jeremy      & 72.73\% & 100.00\% \\ \hline

P012 & Shipi       & 22.22\% & --- \\ \hline
P012 & Juan Andres & 82.35\% & 76.47\% \\ \hline
P012 & Jeremy      & 100.00\% & 100.00\% \\ \hline

P013 & Shipi       & 63.16\% & --- \\ \hline
P013 & Juan Andres & 50.00\% & 75.00\% \\ \hline
P013 & Jeremy      & 84.62\% & 53.85\% \\ \hline

P014 & Shipi       & 57.14\% & --- \\ \hline
P014 & Juan Andres & 50.00\% & 85.71\% \\ \hline
P014 & Jeremy      & 83.33\% & 100.00\% \\ \hline

P015 & Shipi       & 66.67\% & --- \\ \hline
P015 & Juan Andres & 14.29\% & 71.43\% \\ \hline
P015 & Jeremy      & 12.50\% & 100.00\% \\ \hline

P016 & Shipi       & 100.00\% & --- \\ \hline
P016 & Juan Andres & 61.54\% & 84.62\% \\ \hline
P016 & Jeremy      & 100.00\% & 100.00\% \\ \hline

P017 & Shipi       & 46.15\% & --- \\ \hline
P017 & Juan Andres & 55.56\% & 77.78\% \\ \hline
P017 & Jeremy      & 66.67\% & 83.33\% \\ \hline

P018 & Shipi       & 72.73\% & --- \\ \hline
P018 & Juan Andres & 61.11\% & 77.78\% \\ \hline
P018 & Jeremy      & 71.43\% & 100.00\% \\ \hline

P019 & Shipi       & 38.46\% & --- \\ \hline
P019 & Juan Andres & 50.00\% & 50.00\% \\ \hline
P019 & Jeremy      & 50.00\% & 100.00\% \\ \hline

P020 & Shipi       & 41.67\% & --- \\ \hline
P020 & Juan Andres & 42.86\% & 85.71\% \\ \hline
P020 & Jeremy      & 50.00\% & 83.33\% \\ \hline

P021 & Shipi       & 41.67\% & --- \\ \hline
P021 & Juan Andres & 35.71\% & 64.29\% \\ \hline
P021 & Jeremy      & 42.86\% & 100.00\% \\ \hline

P022 & Shipi       & 45.45\% & --- \\ \hline
P022 & Juan Andres & 50.00\% & 83.33\% \\ \hline
P022 & Jeremy      & 87.50\% & 87.50\% \\ \hline

P023 & Shipi       & 38.46\% & --- \\ \hline
P023 & Juan Andres & 63.64\% & 81.82\% \\ \hline
P023 & Jeremy      & 62.50\% & 100.00\% \\ \hline

P024 & Shipi       & 53.85\% & --- \\ \hline
P024 & Juan Andres & 68.42\% & 47.37\% \\ \hline
P024 & Jeremy      & 92.86\% & 85.71\% \\ \hline

P025 & Shipi       & 46.15\% & --- \\ \hline
P025 & Juan Andres & 33.33\% & 83.33\% \\ \hline
P025 & Jeremy      & 90.91\% & 90.91\% \\ \hline

P026 & Shipi       & 70.59\% & --- \\ \hline
P026 & Juan Andres & 60.00\% & 68.57\% \\ \hline
P026 & Jeremy      & 100.00\% & 87.50\% \\ \hline

P027 & Shipi       & 80.00\% & --- \\ \hline
P027 & Juan Andres & 60.00\% & 93.33\% \\ \hline
P027 & Jeremy      & 83.33\% & 100.00\% \\ \hline

P028 & Shipi       & 50.00\% & --- \\ \hline
P028 & Juan Andres & 63.16\% & 47.37\% \\ \hline
P028 & Jeremy      & 33.33\% & 83.33\% \\ \hline

P029 & Shipi       & 11.11\% & --- \\ \hline
P029 & Juan Andres & 43.75\% & 93.75\% \\ \hline
P029 & Jeremy      & 62.50\% & 100.00\% \\ \hline

P030 & Shipi       & 41.67\% & --- \\ \hline
P030 & Juan Andres & 56.25\% & 87.50\% \\ \hline
P030 & Jeremy      & 85.71\% & 100.00\% \\ \hline

P031 & Shipi       & 50.00\% & --- \\ \hline
P031 & Juan Andres & 47.06\% & 70.59\% \\ \hline
P031 & Jeremy      & 85.71\% & 100.00\% \\ \hline

P032 & Shipi       & 70.00\% & --- \\ \hline
P032 & Juan Andres & 52.94\% & 82.35\% \\ \hline
P032 & Jeremy      & 57.14\% & 85.71\% \\ \hline

P033 & Shipi       & 87.50\% & --- \\ \hline
P033 & Juan Andres & 16.67\% & 50.00\% \\ \hline
P033 & Jeremy      & 71.43\% & 85.71\% \\ \hline

P034 & Shipi       & 58.82\% & --- \\ \hline
P034 & Juan Andres & 72.22\% & 88.89\% \\ \hline
P034 & Jeremy      & 85.71\% & 100.00\% \\ \hline

P036 & Shipi       & 41.67\% & --- \\ \hline
P036 & Juan Andres & 38.89\% & 66.67\% \\ \hline
P036 & Jeremy      & 87.50\% & 100.00\% \\ \hline

In [8]:
import pandas as pd
from pathlib import Path
import re

# Carpeta donde está tu notebook
carpeta = Path(r"C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results\Metricas\Convertidos")

# Buscar únicamente archivos de todos los eventos
archivos = sorted(carpeta.rglob("*_todos_eventos.csv"))

print(f"Archivos encontrados: {len(archivos)}")

dataframes = []

for archivo in archivos:
    df = pd.read_csv(archivo, encoding="utf-8-sig")

    # Extraer participante del nombre del archivo
    # Ejemplo: Metrics_P001_2026-10-02_12-23-37_todos_eventos.csv
    match = re.search(r"P\d+", archivo.name)

    participante = match.group() if match else "Desconocido"

    df["Participante"] = participante
    df["ArchivoOrigen"] = archivo.name

    dataframes.append(df)

# Unir los CSV
if not dataframes:
    raise FileNotFoundError("No se encontraron archivos de todos los eventos")

df_eventos = pd.concat(dataframes, ignore_index=True)

# Guardar CSV unificado
salida = Path(r"C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results") / "todos_eventos_unificados.csv"

df_eventos.to_csv(
    salida,
    index=False,
    encoding="utf-8-sig"
)

print(f"Total de eventos: {len(df_eventos)}")
print(f"Participantes: {df_eventos['Participante'].nunique()}")
print(f"CSV guardado en: {salida}")

display(df_eventos.head(10))

Archivos encontrados: 34
Total de eventos: 6060
Participantes: 34
CSV guardado en: C:\Users\Lenovo _ LeGion\Documents\Universidad\Trabajo de Graduacion\Latex\PGL\raw results\todos_eventos_unificados.csv

,IdEvento,FechaHora,Categoria,Minijuego,TipoAccion,Resultado,Dificultad,EstadoJugador,CambioDificultad,Motivo,ErrorTiming_s,TiempoReaccion_s,LineaOrigen,TextoOriginal,Participante,ArchivoOrigen
0,1,2026-10-02 14:30:46.028,PlayerState,NaN,NaN,NaN,NaN,Idle,NaN,NaN,NaN,NaN,6,2026-10-02 14:30:46.028 | PlayerState: Idle,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
1,2,2026-10-02 14:30:47.911,Interaction,Alex,HammerTouch,Success,Normal,NaN,NaN,NaN,NaN,NaN,7,2026-10-02 14:30:47.911 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
2,3,2026-10-02 14:30:47.911,PlayerState,NaN,NaN,NaN,NaN,Engaged,NaN,NaN,NaN,NaN,8,2026-10-02 14:30:47.911 | PlayerState: Engaged,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
3,4,2026-10-02 14:30:48.674,Interaction,Alex,HammerTouch,Success,Normal,NaN,NaN,NaN,NaN,NaN,9,2026-10-02 14:30:48.674 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
4,5,2026-10-02 14:30:48.729,Interaction,Alex,HammerTouch,Success,Normal,NaN,NaN,NaN,NaN,NaN,10,2026-10-02 14:30:48.729 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
5,6,2026-10-02 14:30:49.440,Interaction,Alex,HammerHit,Success,Normal,NaN,NaN,NaN,0.0115,NaN,11,2026-10-02 14:30:49.440 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
6,7,2026-10-02 14:30:49.494,Interaction,Alex,HammerTouch,Success,Normal,NaN,NaN,NaN,NaN,NaN,12,2026-10-02 14:30:49.494 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
7,8,2026-10-02 14:30:50.204,Interaction,Alex,HammerHit,Failed,Normal,NaN,NaN,NaN,0.0079,NaN,13,2026-10-02 14:30:50.204 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
8,9,2026-10-02 14:30:50.522,Interaction,Alex,HammerTouch,Missed,Normal,NaN,NaN,NaN,NaN,NaN,14,2026-10-02 14:30:50.522 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...
9,10,2026-10-02 14:30:50.954,Interaction,Alex,HammerHit,Success,Normal,NaN,NaN,NaN,0.0099,NaN,15,2026-10-02 14:30:50.954 | Minigame: Alex | Typ...,P0011,Metrics_P0011_2026-10-02_14-30-44_todos_evento...

In [9]:
import pandas as pd

# Filtrar únicamente los eventos de estado del jugador
df_estados = df_eventos[
    df_eventos["Categoria"] == "PlayerState"
].copy()

# Contar las apariciones de cada estado por participante
conteo_estados = pd.crosstab(
    df_estados["Participante"],
    df_estados["EstadoJugador"]
)

# Asegurar el orden de las columnas
conteo_estados = conteo_estados.reindex(
    columns=["Idle", "Engaged", "Overloaded"],
    fill_value=0
)

# Agregar total de cambios de estado
conteo_estados["Total"] = conteo_estados.sum(axis=1)

# Mostrar resultados
display(conteo_estados)

EstadoJugador  Idle  Engaged  Overloaded  Total
Participante
P001              8       12           7     27
P0011             7       10           7     24
P002              8       14           7     29
P003              5       11          10     26
P004              8       11           5     24
P005              7        9           4     20
P006              6        9           4     19
P007              6       10           6     22
P008              5        9           7     21
P010              8       11           5     24
P012              4       10           7     21
P013              8       13           6     27
P014              7       10           5     22
P015              8       12           8     28
P016              8       11           5     24
P017              6       10           7     23
P018              6       11           7     24
P019              7       10           6     23
P020              9       12           6     27
P021              8       13           9     30
P022              7       11           6     24
P023              5        8           6     19
P024              5        8           4     17
P025              7       13           8     28
P026              6        9           5     20
P027              5        8           5     18
P028              7        9           7     23
P029              6        8           5     19
P030              9       14           6     29
P031              8       10           4     22
P032              4       10           8     22
P033              8       13           8     29
P034              4        7           5     16
P036              5       11           7     23

In [10]:
for participante, fila in conteo_estados.iterrows():
    print(
        f"{participante} & {fila['Idle']} & "
        f"{fila['Engaged']} & {fila['Overloaded']} & "
        f"{fila['Total']} " + r"\\ \hline"
    )

P001 & 8 & 12 & 7 & 27 \\ \hline
P0011 & 7 & 10 & 7 & 24 \\ \hline
P002 & 8 & 14 & 7 & 29 \\ \hline
P003 & 5 & 11 & 10 & 26 \\ \hline
P004 & 8 & 11 & 5 & 24 \\ \hline
P005 & 7 & 9 & 4 & 20 \\ \hline
P006 & 6 & 9 & 4 & 19 \\ \hline
P007 & 6 & 10 & 6 & 22 \\ \hline
P008 & 5 & 9 & 7 & 21 \\ \hline
P010 & 8 & 11 & 5 & 24 \\ \hline
P012 & 4 & 10 & 7 & 21 \\ \hline
P013 & 8 & 13 & 6 & 27 \\ \hline
P014 & 7 & 10 & 5 & 22 \\ \hline
P015 & 8 & 12 & 8 & 28 \\ \hline
P016 & 8 & 11 & 5 & 24 \\ \hline
P017 & 6 & 10 & 7 & 23 \\ \hline
P018 & 6 & 11 & 7 & 24 \\ \hline
P019 & 7 & 10 & 6 & 23 \\ \hline
P020 & 9 & 12 & 6 & 27 \\ \hline
P021 & 8 & 13 & 9 & 30 \\ \hline
P022 & 7 & 11 & 6 & 24 \\ \hline
P023 & 5 & 8 & 6 & 19 \\ \hline
P024 & 5 & 8 & 4 & 17 \\ \hline
P025 & 7 & 13 & 8 & 28 \\ \hline
P026 & 6 & 9 & 5 & 20 \\ \hline
P027 & 5 & 8 & 5 & 18 \\ \hline
P028 & 7 & 9 & 7 & 23 \\ \hline
P029 & 6 & 8 & 5 & 19 \\ \hline
P030 & 9 & 14 & 6 & 29 \\ \hline
P031 & 8 & 10 & 4 & 22 \\ \hline
P032 & 4 & 10 & 8 & 22 \\ \hline
P033 & 8 & 13 & 8 & 29 \\ \hline
P034 & 4 & 7 & 5 & 16 \\ \hline
P036 & 5 & 11 & 7 & 23 \\ \hline